import type { Metadata } from "next";
import { AppProps } from "next/app";
// import localFont from "next/font/local";
import {  geistMono, poppins } from "../utils/fonts";
import '@/styles/globals.css';

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MyApp({ Component, pageProps }: AppProps) {
    return (
        <div className={`${poppins.className} ${geistMono.variable} antialiased`}>
            <Component {...pageProps} />
        </div>
    );
}